services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
    env_file:
      - .env
    command: npm run watch